name: Test SSH Connection

on:
  workflow_dispatch:

jobs:
  test-ssh:
    runs-on: ubuntu-latest

    steps:
      - name: Prepare SSH key
        run: |
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > github_actions_key
          chmod 600 github_actions_key

      - name: Check server
        run: |
          ssh -o StrictHostKeyChecking=no \
            -i github_actions_key \
            likafom@${{ secrets.SERVER_HOST }} \
            "nginx -v"